package com.financeiro.adapters.in.web;
import com.financeiro.application.pagination.Paginacao; import com.financeiro.application.ports.in.CartaoCreditoUseCase; import com.financeiro.application.ports.in.FinanceiroCoreUseCase; import com.financeiro.domain.model.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.HttpStatus; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.oauth2.jwt.Jwt; import org.springframework.validation.annotation.Validated; import org.springframework.web.bind.annotation.*; import java.math.BigDecimal; import java.time.LocalDate; import java.util.List;
@RestController @RequestMapping("/api/v1/cartoes") @Validated public class CartaoCreditoController {
 private final CartaoCreditoUseCase useCase; public CartaoCreditoController(CartaoCreditoUseCase useCase){this.useCase=useCase;}
 @GetMapping PaginaResponse<CartaoResponse> listar(@AuthenticationPrincipal Jwt j,@RequestParam(defaultValue="0") @PositiveOrZero int pagina,@RequestParam(defaultValue="20") @Min(1) @Max(100) int tamanho){return PaginaResponse.from(useCase.listarCartoes(id(j),new Paginacao(pagina,tamanho)).map(CartaoResponse::from));}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) CartaoResponse criar(@AuthenticationPrincipal Jwt j,@Valid @RequestBody CartaoRequest r){return CartaoResponse.from(useCase.criarCartao(id(j),new CartaoCreditoUseCase.CriarCartaoCommand(r.nome(),r.limite(),r.diaFechamento(),r.diaVencimento())));}
 @GetMapping("/{cartaoId}") CartaoResponse buscar(@AuthenticationPrincipal Jwt j,@PathVariable @Positive Long cartaoId){return CartaoResponse.from(useCase.buscarCartao(id(j),cartaoId));}
 @PatchMapping("/{cartaoId}") CartaoResponse atualizar(@AuthenticationPrincipal Jwt j,@PathVariable @Positive Long cartaoId,@Valid @RequestBody CartaoRequest r){return CartaoResponse.from(useCase.atualizarCartao(id(j),cartaoId,new CartaoCreditoUseCase.CriarCartaoCommand(r.nome(),r.limite(),r.diaFechamento(),r.diaVencimento())));}
 @DeleteMapping("/{cartaoId}") @ResponseStatus(HttpStatus.NO_CONTENT) void inativar(@AuthenticationPrincipal Jwt j,@PathVariable @Positive Long cartaoId){useCase.inativarCartao(id(j),cartaoId);}
 @GetMapping("/{cartaoId}/faturas") PaginaResponse<FaturaResponse> faturas(@AuthenticationPrincipal Jwt j,@PathVariable @Positive Long cartaoId,@RequestParam(defaultValue="0") @PositiveOrZero int pagina,@RequestParam(defaultValue="20") @Min(1) @Max(100) int tamanho){return PaginaResponse.from(useCase.listarFaturas(id(j),cartaoId,new Paginacao(pagina,tamanho)).map(FaturaResponse::from));}
 @PostMapping("/faturas") @ResponseStatus(HttpStatus.CREATED) FaturaResponse criarFatura(@AuthenticationPrincipal Jwt j,@Valid @RequestBody FaturaRequest r){return FaturaResponse.from(useCase.criarFatura(id(j),new CartaoCreditoUseCase.CriarFaturaCommand(r.cartaoId(),r.anoMes(),r.dataFechamento(),r.dataVencimento(),r.contaPagamentoId())));}
 @PostMapping("/faturas/{faturaId}/gastos") @ResponseStatus(HttpStatus.CREATED) FinanceiroCoreController.TransacaoResponse gasto(@AuthenticationPrincipal Jwt j,@PathVariable @Positive Long faturaId,@Valid @RequestBody GastoRequest r){var itens=r.itens()==null?List.<FinanceiroCoreUseCase.ItemCommand>of():r.itens().stream().map(i->new FinanceiroCoreUseCase.ItemCommand(i.descricao(),i.valor(),i.categoriaId())).toList();return FinanceiroCoreController.TransacaoResponse.from(useCase.lancarGasto(id(j),new CartaoCreditoUseCase.LancarGastoCommand(faturaId,r.valor(),r.data(),r.descricao(),r.contaId(),r.categoriaId(),itens)));}
 @PostMapping("/faturas/{faturaId}/fechar") FaturaResponse fechar(@AuthenticationPrincipal Jwt j,@PathVariable @Positive Long faturaId){return FaturaResponse.from(useCase.fechar(id(j),faturaId));} @GetMapping("/faturas/{faturaId}") FaturaResponse buscarFatura(@AuthenticationPrincipal Jwt j,@PathVariable @Positive Long faturaId){return FaturaResponse.from(useCase.buscarFatura(id(j),faturaId));} @PostMapping("/faturas/{faturaId}/pagar") FaturaResponse pagar(@AuthenticationPrincipal Jwt j,@PathVariable @Positive Long faturaId,@Valid @RequestBody PagamentoRequest r){return FaturaResponse.from(useCase.pagar(id(j),faturaId,r.dataPagamento()));}
 private Long id(Jwt j){return Long.valueOf(j.getSubject());}
 record CartaoRequest(@NotBlank @Size(max=100)String nome,@NotNull @DecimalMin("0.01")BigDecimal limite,@Min(1)@Max(31)int diaFechamento,@Min(1)@Max(31)int diaVencimento){} record FaturaRequest(@NotNull @Positive Long cartaoId,@NotBlank @Pattern(regexp="\\d{4}-\\d{2}")String anoMes,@NotNull LocalDate dataFechamento,@NotNull LocalDate dataVencimento,@NotNull @Positive Long contaPagamentoId){} record PagamentoRequest(@NotNull LocalDate dataPagamento){} record GastoRequest(@NotNull @DecimalMin("0.01")BigDecimal valor,@NotNull LocalDate data,@NotBlank @Size(max=500)String descricao,@NotNull @Positive Long contaId,@Positive Long categoriaId,List<@Valid ItemRequest> itens){} record ItemRequest(@NotBlank String descricao,@NotNull @DecimalMin("0.01")BigDecimal valor,@Positive Long categoriaId){} record CartaoResponse(Long id,String nome,BigDecimal limite,int diaFechamento,int diaVencimento,boolean ativo){static CartaoResponse from(CartaoCredito c){return new CartaoResponse(c.getId(),c.getNome(),c.getLimite().valor(),c.getDiaFechamento(),c.getDiaVencimento(),c.isAtivo());}} record FaturaResponse(Long id,Long cartaoId,String anoMes,LocalDate fechamento,LocalDate vencimento,StatusFatura status,Long contaPagamentoId){static FaturaResponse from(Fatura f){return new FaturaResponse(f.getId(),f.getCartaoId(),f.getMesReferencia().formatado(),f.getDataFechamento(),f.getDataVencimento(),f.getStatus(),f.getContaPagamentoId());}}
}
